# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0037_userprofile_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionlog',
            name='campus',
            field=models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalink.campus'),
        ),
    ]
