# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0038_positionlog_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftPositionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(db_index=True, null=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('altitude', models.FloatField(null=True)),
                ('ground_speed', models.FloatField(null=True)),
                ('ground_track', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_on', models.DateField(db_index=True, null=True)),
                ('aircraft', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to='evalink.aircraft')),
                ('campus', models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalink.campus')),
            ],
        ),
    ]
