"""
Django settings for evalink project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sys

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def _csv_env(name, default=''):
    raw = os.getenv(name, default) or ''
    return [item.strip() for item in raw.split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-t)=ssk9r_e_yxde^s2%+j4nz1ol&tk0hr7ge98qgc9%yc&5wxd',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '1') not in ('0', 'false', 'False', '')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'evalink',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'evalink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evalink.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  
        'HOST': os.getenv('HOST'),
        'NAME': os.getenv('NAME'),
        'PORT': os.getenv('PORT'),
        'USER': os.getenv('DBUSER'),
        'PASSWORD': (os.getenv('PASSWORD') or os.getenv('POSTGRES_PASSWORD') or '').strip(),
        'OPTIONS': {'sslmode': os.getenv('SSLMODE')},
    }
}

# Test database configuration
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('HOST', 'localhost'),
        'NAME': os.getenv('NAME', 'test_db'),
        'PORT': os.getenv('PORT', '5432'),
        'USER': os.getenv('DBUSER', 'postgres'),
        'PASSWORD': os.getenv('PASSWORD', 'postgres'),
        'OPTIONS': {'sslmode': os.getenv('SSLMODE', 'disable')},
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Denver'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.getenv('STATIC_ROOT')
MEDIA_ROOT = os.getenv('MEDIA_ROOT')

# Whitenoise serves the collected static files directly from the web
# container so we don't need a separate nginx in front of Django. Use the
# non-manifest storage so tests (which don't run collectstatic) still work.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Defaults preserve the historical hostname list; override with env in
# production to add the Cloudflare-fronted hostnames.
_DEFAULT_HOSTS = 'evalink03.westus3.cloudapp.azure.com,evalink.archresearch.net,localhost,127.0.0.1,evalink,radmac.local'
_DEFAULT_CSRF = 'https://evalink03.westus3.cloudapp.azure.com,https://evalink.archresearch.net'

ALLOWED_HOSTS = _csv_env('DJANGO_ALLOWED_HOSTS', _DEFAULT_HOSTS)
# ZimaOS / LAN access by IP (e.g. http://192.168.x.x:18000) without listing every IP.
if os.getenv('DJANGO_ALLOW_LAN', '0') in ('1', 'true', 'True') and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = ALLOWED_HOSTS + ['*']
CSRF_TRUSTED_ORIGINS = _csv_env('DJANGO_CSRF_TRUSTED_ORIGINS', _DEFAULT_CSRF)

# Cloudflare terminates TLS in front of us; trust the X-Forwarded-Proto
# header so request.is_secure() returns the real value and Django generates
# https:// absolute URLs.
if os.getenv('DJANGO_BEHIND_PROXY', '0') in ('1', 'true', 'True'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

LOGGING_CONFIG = None
